import Head from "next/head";
import styles from "@/styles/Home.module.sass";
import React, { useState } from "react";

import ColorSlider from "@/components/Slider";
import Header from "@/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kandinsky</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div
          style={{
            border: "1px solid red",
            position: "absolute",
            height: "100%",
            margin: "0 auto",
          }}
        ></div> */}
        <Header />
        <ColorSlider />
      </main>
    </>
  );
}
