import Head from "next/head";
import styles from "@/styles/Home.module.sass";
import ColorSlider from "@/components/Slider";
import React, { useState } from "react";
import NonLinearSlider from "@/components/RangeSlider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kandinsky</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ColorSlider />
      </main>
    </>
  );
}
